import Head from "next/head";
import HomePage from "../components/HomePage";

export default function Home() {
  return (
    <div className="min-h-screen w-screen">
      <Head>
        <title>Formik Login</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://img.stackshare.io/service/8846/preview.png"
        />
      </Head>
      <HomePage />
    </div>
  );
}
